<?php
namespace lib\app;


class translate
{

	public static function list()
	{
		$translate =
		[
			'am_sadiq'           => ['language' => 'am'],
			'ar_jalalayn'        => ['language' => 'ar'],
			'ar_muyassar'        => ['language' => 'ar'],
			'az_mammadaliyev'    => ['language' => 'az'],
			'az_musayev'         => ['language' => 'az'],
			'be_.mensur'         => ['language' => 'be'],
			'bg_theophanov'      => ['language' => 'bg'],
			'bn_bengali'         => ['language' => 'bn'],
			'bn_hoque'           => ['language' => 'bn'],
			'bs_korkut'          => ['language' => 'bs'],
			'bs_mlivo'           => ['language' => 'bs'],
			'cs_hrbek'           => ['language' => 'cs'],
			'cs_nykl'            => ['language' => 'cs'],
			'de_aburida'         => ['language' => 'de'],
			'de_bubenheim'       => ['language' => 'de'],
			'de_khoury'          => ['language' => 'de'],
			'de_zaidan'          => ['language' => 'de'],
			'dv_divehi'          => ['language' => 'dv'],
			'en_ahmedali'        => ['language' => 'en'],
			'en_ahmedraza'       => ['language' => 'en'],
			'en_arberry'         => ['language' => 'en'],
			'en_daryabadi'       => ['language' => 'en'],
			'en_hilali'          => ['language' => 'en'],
			'en_itani'           => ['language' => 'en'],
			'en_maududi'         => ['language' => 'en'],
			'en_mubarakpuri'     => ['language' => 'en'],
			'en_pickthall'       => ['language' => 'en'],
			'en_qarai'           => ['language' => 'en'],
			'en_qaribullah'      => ['language' => 'en'],
			'en_sahih'           => ['language' => 'en'],
			'en_sarwar'          => ['language' => 'en'],
			'en_shakir'          => ['language' => 'en'],
			'en_transliteration' => ['language' => 'en'],
			'en_wahiduddin'      => ['language' => 'en'],
			'en_yusufali'        => ['language' => 'en'],
			'es_bornez'          => ['language' => 'es'],
			'es_cortes'          => ['language' => 'es'],
			'es_garcia'          => ['language' => 'es'],
			'fa_ansarian'        => ['language' => 'fa'],
			'fa_ayati'           => ['language' => 'fa'],
			'fa_bahrampour'      => ['language' => 'fa'],
			'fa_fooladvand'      => ['language' => 'fa'],
			'fa_gharaati'        => ['language' => 'fa'],
			'fa_ghomshei'        => ['language' => 'fa'],
			'fa_khorramdel'      => ['language' => 'fa'],
			'fa_khorramshahi'    => ['language' => 'fa'],
			'fa_makarem'         => ['language' => 'fa'],
			'fa_moezzi'          => ['language' => 'fa'],
			'fa_mojtabavi'       => ['language' => 'fa'],
			'fa_sadeqi'          => ['language' => 'fa'],
			'fr_hamidullah'      => ['language' => 'fr'],
			'ha_gumi'            => ['language' => 'ha'],
			'hi_farooq'          => ['language' => 'hi'],
			'hi_hindi'           => ['language' => 'hi'],
			'id_indonesian'      => ['language' => 'id'],
			'id_jalalayn'        => ['language' => 'id'],
			'id_muntakhab'       => ['language' => 'id'],
			'it_piccardo'        => ['language' => 'it'],
			'ja_japanese'        => ['language' => 'ja'],
			'ko_korean'          => ['language' => 'ko'],
			'ku_asan'            => ['language' => 'ku'],
			'ml_abdulhameed'     => ['language' => 'ml'],
			'ml_karakunnu'       => ['language' => 'ml'],
			'ms_basmeih'         => ['language' => 'ms'],
			'nl_keyzer'          => ['language' => 'nl'],
			'nl_leemhuis'        => ['language' => 'nl'],
			'nl_siregar'         => ['language' => 'nl'],
			'no_berg'            => ['language' => 'no'],
			'pl_bielawskiego'    => ['language' => 'pl'],
			'ps_abdulwali'       => ['language' => 'ps'],
			'pt_elhayek'         => ['language' => 'pt'],
			'ro_grigore'         => ['language' => 'ro'],
			'ru_abuadel'         => ['language' => 'ru'],
			'ru_krachkovsky'     => ['language' => 'ru'],
			'ru_kuliev'          => ['language' => 'ru'],
			'ru_muntahab'        => ['language' => 'ru'],
			'ru_osmanov'         => ['language' => 'ru'],
			'ru_porokhova'       => ['language' => 'ru'],
			'ru_sablukov'        => ['language' => 'ru'],
			'sd_amroti'          => ['language' => 'sd'],
			'so_abduh'           => ['language' => 'so'],
			'sq_ahmeti'          => ['language' => 'sq'],
			'sq_mehdiu'          => ['language' => 'sq'],
			'sq_nahi'            => ['language' => 'sq'],
			'sv_bernstrom'       => ['language' => 'sv'],
			'sw_barwani'         => ['language' => 'sw'],
			'ta_tamil'           => ['language' => 'ta'],
			'tg_ayati'           => ['language' => 'tg'],
			'th_thai'            => ['language' => 'th'],
			'tr_ates'            => ['language' => 'tr'],
			'tr_bulac'           => ['language' => 'tr'],
			'tr_diyanet'         => ['language' => 'tr'],
			'tr_golpinarli'      => ['language' => 'tr'],
			'tr_ozturk'          => ['language' => 'tr'],
			'tr_transliteration' => ['language' => 'tr'],
			'tr_vakfi'           => ['language' => 'tr'],
			'tr_yazir'           => ['language' => 'tr'],
			'tr_yildirim'        => ['language' => 'tr'],
			'tr_yuksel'          => ['language' => 'tr'],
			'tt_nugman'          => ['language' => 'tt'],
			'ug_saleh'           => ['language' => 'ug'],
			'ur_ahmedali'        => ['language' => 'ur'],
			'ur_jalandhry'       => ['language' => 'ur'],
			'ur_jawadi'          => ['language' => 'ur'],
			'ur_junagarhi'       => ['language' => 'ur'],
			'ur_kanzuliman'      => ['language' => 'ur'],
			'ur_maududi'         => ['language' => 'ur'],
			'ur_najafi'          => ['language' => 'ur'],
			'ur_qadri'           => ['language' => 'ur'],
			'uz_sodik'           => ['language' => 'uz'],
			'zh_jian'            => ['language' => 'zh'],
			'zh_majian'          => ['language' => 'zh'],
		];
		return $translate;
	}
}
?>