<?php
namespace lib\app;


class translate
{

	public static function list()
	{
		$translate =
		[
			'am_sadiq'           => ['language' => 'am', 'name' => 'sadiq'],
			'ar_jalalayn'        => ['language' => 'ar', 'name' => 'jalalayn'],
			'ar_muyassar'        => ['language' => 'ar', 'name' => 'muyassar'],
			'az_mammadaliyev'    => ['language' => 'az', 'name' => 'mammadaliyev'],
			'az_musayev'         => ['language' => 'az', 'name' => 'musayev'],
			'be_mensur'          => ['language' => 'be', 'name' => 'mensur'],
			'bg_theophanov'      => ['language' => 'bg', 'name' => 'theophanov'],
			'bn_bengali'         => ['language' => 'bn', 'name' => 'bengali'],
			'bn_hoque'           => ['language' => 'bn', 'name' => 'hoque'],
			'bs_korkut'          => ['language' => 'bs', 'name' => 'korkut'],
			'bs_mlivo'           => ['language' => 'bs', 'name' => 'mlivo'],
			'cs_hrbek'           => ['language' => 'cs', 'name' => 'hrbek'],
			'cs_nykl'            => ['language' => 'cs', 'name' => 'nykl'],
			'de_aburida'         => ['language' => 'de', 'name' => 'aburida'],
			'de_bubenheim'       => ['language' => 'de', 'name' => 'bubenheim'],
			'de_khoury'          => ['language' => 'de', 'name' => 'khoury'],
			'de_zaidan'          => ['language' => 'de', 'name' => 'zaidan'],
			'dv_divehi'          => ['language' => 'dv', 'name' => 'divehi'],
			'en_ahmedali'        => ['language' => 'en', 'name' => 'ahmedali'],
			'en_ahmedraza'       => ['language' => 'en', 'name' => 'ahmedraza'],
			'en_arberry'         => ['language' => 'en', 'name' => 'arberry'],
			'en_daryabadi'       => ['language' => 'en', 'name' => 'daryabadi'],
			'en_hilali'          => ['language' => 'en', 'name' => 'hilali'],
			'en_itani'           => ['language' => 'en', 'name' => 'itani'],
			'en_maududi'         => ['language' => 'en', 'name' => 'maududi'],
			'en_mubarakpuri'     => ['language' => 'en', 'name' => 'mubarakpuri'],
			'en_pickthall'       => ['language' => 'en', 'name' => 'pickthall'],
			'en_qarai'           => ['language' => 'en', 'name' => 'qarai'],
			'en_qaribullah'      => ['language' => 'en', 'name' => 'qaribullah'],
			'en_sahih'           => ['language' => 'en', 'name' => 'sahih'],
			'en_sarwar'          => ['language' => 'en', 'name' => 'sarwar'],
			'en_shakir'          => ['language' => 'en', 'name' => 'shakir'],
			'en_transliteration' => ['language' => 'en', 'name' => 'transliteration'],
			'en_wahiduddin'      => ['language' => 'en', 'name' => 'wahiduddin'],
			'en_yusufali'        => ['language' => 'en', 'name' => 'yusufali'],
			'es_bornez'          => ['language' => 'es', 'name' => 'bornez'],
			'es_cortes'          => ['language' => 'es', 'name' => 'cortes'],
			'es_garcia'          => ['language' => 'es', 'name' => 'garcia'],
			'fa_ansarian'        => ['language' => 'fa', 'name' => 'ansarian'],
			'fa_ayati'           => ['language' => 'fa', 'name' => 'ayati'],
			'fa_bahrampour'      => ['language' => 'fa', 'name' => 'bahrampour'],
			'fa_fooladvand'      => ['language' => 'fa', 'name' => 'fooladvand'],
			'fa_gharaati'        => ['language' => 'fa', 'name' => 'gharaati'],
			'fa_ghomshei'        => ['language' => 'fa', 'name' => 'ghomshei'],
			'fa_khorramdel'      => ['language' => 'fa', 'name' => 'khorramdel'],
			'fa_khorramshahi'    => ['language' => 'fa', 'name' => 'khorramshahi'],
			'fa_makarem'         => ['language' => 'fa', 'name' => 'makarem'],
			'fa_moezzi'          => ['language' => 'fa', 'name' => 'moezzi'],
			'fa_mojtabavi'       => ['language' => 'fa', 'name' => 'mojtabavi'],
			'fa_sadeqi'          => ['language' => 'fa', 'name' => 'sadeqi'],
			'fr_hamidullah'      => ['language' => 'fr', 'name' => 'hamidullah'],
			'ha_gumi'            => ['language' => 'ha', 'name' => 'gumi'],
			'hi_farooq'          => ['language' => 'hi', 'name' => 'farooq'],
			'hi_hindi'           => ['language' => 'hi', 'name' => 'hindi'],
			'id_indonesian'      => ['language' => 'id', 'name' => 'indonesian'],
			'id_jalalayn'        => ['language' => 'id', 'name' => 'jalalayn'],
			'id_muntakhab'       => ['language' => 'id', 'name' => 'muntakhab'],
			'it_piccardo'        => ['language' => 'it', 'name' => 'piccardo'],
			'ja_japanese'        => ['language' => 'ja', 'name' => 'japanese'],
			'ko_korean'          => ['language' => 'ko', 'name' => 'korean'],
			'ku_asan'            => ['language' => 'ku', 'name' => 'asan'],
			'ml_abdulhameed'     => ['language' => 'ml', 'name' => 'abdulhameed'],
			'ml_karakunnu'       => ['language' => 'ml', 'name' => 'karakunnu'],
			'ms_basmeih'         => ['language' => 'ms', 'name' => 'basmeih'],
			'nl_keyzer'          => ['language' => 'nl', 'name' => 'keyzer'],
			'nl_leemhuis'        => ['language' => 'nl', 'name' => 'leemhuis'],
			'nl_siregar'         => ['language' => 'nl', 'name' => 'siregar'],
			'no_berg'            => ['language' => 'no', 'name' => 'berg'],
			'pl_bielawskiego'    => ['language' => 'pl', 'name' => 'bielawskiego'],
			'ps_abdulwali'       => ['language' => 'ps', 'name' => 'abdulwali'],
			'pt_elhayek'         => ['language' => 'pt', 'name' => 'elhayek'],
			'ro_grigore'         => ['language' => 'ro', 'name' => 'grigore'],
			'ru_abuadel'         => ['language' => 'ru', 'name' => 'abuadel'],
			'ru_krachkovsky'     => ['language' => 'ru', 'name' => 'krachkovsky'],
			'ru_kuliev'          => ['language' => 'ru', 'name' => 'kuliev'],
			'ru_muntahab'        => ['language' => 'ru', 'name' => 'muntahab'],
			'ru_osmanov'         => ['language' => 'ru', 'name' => 'osmanov'],
			'ru_porokhova'       => ['language' => 'ru', 'name' => 'porokhova'],
			'ru_sablukov'        => ['language' => 'ru', 'name' => 'sablukov'],
			'sd_amroti'          => ['language' => 'sd', 'name' => 'amroti'],
			'so_abduh'           => ['language' => 'so', 'name' => 'abduh'],
			'sq_ahmeti'          => ['language' => 'sq', 'name' => 'ahmeti'],
			'sq_mehdiu'          => ['language' => 'sq', 'name' => 'mehdiu'],
			'sq_nahi'            => ['language' => 'sq', 'name' => 'nahi'],
			'sv_bernstrom'       => ['language' => 'sv', 'name' => 'bernstrom'],
			'sw_barwani'         => ['language' => 'sw', 'name' => 'barwani'],
			'ta_tamil'           => ['language' => 'ta', 'name' => 'tamil'],
			'tg_ayati'           => ['language' => 'tg', 'name' => 'ayati'],
			'th_thai'            => ['language' => 'th', 'name' => 'thai'],
			'tr_ates'            => ['language' => 'tr', 'name' => 'ates'],
			'tr_bulac'           => ['language' => 'tr', 'name' => 'bulac'],
			'tr_diyanet'         => ['language' => 'tr', 'name' => 'diyanet'],
			'tr_golpinarli'      => ['language' => 'tr', 'name' => 'golpinarli'],
			'tr_ozturk'          => ['language' => 'tr', 'name' => 'ozturk'],
			'tr_transliteration' => ['language' => 'tr', 'name' => 'transliteration'],
			'tr_vakfi'           => ['language' => 'tr', 'name' => 'vakfi'],
			'tr_yazir'           => ['language' => 'tr', 'name' => 'yazir'],
			'tr_yildirim'        => ['language' => 'tr', 'name' => 'yildirim'],
			'tr_yuksel'          => ['language' => 'tr', 'name' => 'yuksel'],
			'tt_nugman'          => ['language' => 'tt', 'name' => 'nugman'],
			'ug_saleh'           => ['language' => 'ug', 'name' => 'saleh'],
			'ur_ahmedali'        => ['language' => 'ur', 'name' => 'ahmedali'],
			'ur_jalandhry'       => ['language' => 'ur', 'name' => 'jalandhry'],
			'ur_jawadi'          => ['language' => 'ur', 'name' => 'jawadi'],
			'ur_junagarhi'       => ['language' => 'ur', 'name' => 'junagarhi'],
			'ur_kanzuliman'      => ['language' => 'ur', 'name' => 'kanzuliman'],
			'ur_maududi'         => ['language' => 'ur', 'name' => 'maududi'],
			'ur_najafi'          => ['language' => 'ur', 'name' => 'najafi'],
			'ur_qadri'           => ['language' => 'ur', 'name' => 'qadri'],
			'uz_sodik'           => ['language' => 'uz', 'name' => 'sodik'],
			'zh_jian'            => ['language' => 'zh', 'name' => 'jian'],
			'zh_majian'          => ['language' => 'zh', 'name' => 'majian'],
		];
		return $translate;
	}
}
?>