UPDATE sure SET sure.tname = 'Al-Fatihah' , sure.ename = 'The Opener' WHERE sure.index = 1 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Baqarah' , sure.ename = 'The Cow' WHERE sure.index = 2 LIMIT 1;
UPDATE sure SET sure.tname = 'Ali \'Imran' , sure.ename = 'Family of Imran' WHERE sure.index = 3 LIMIT 1;
UPDATE sure SET sure.tname = 'An-Nisa' , sure.ename = 'The Women' WHERE sure.index = 4 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Ma\'idah' , sure.ename = 'The Table Spread' WHERE sure.index = 5 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-An\'am' , sure.ename = 'The Cattle' WHERE sure.index = 6 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-A\'raf' , sure.ename = 'The Heights' WHERE sure.index = 7 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Anfal' , sure.ename = 'The Spoils of War' WHERE sure.index = 8 LIMIT 1;
UPDATE sure SET sure.tname = 'At-Tawbah' , sure.ename = 'The Repentance' WHERE sure.index = 9 LIMIT 1;
UPDATE sure SET sure.tname = 'Yunus' , sure.ename = 'Jonah' WHERE sure.index = 10 LIMIT 1;
UPDATE sure SET sure.tname = 'Hud' , sure.ename = 'Hud' WHERE sure.index = 11 LIMIT 1;
UPDATE sure SET sure.tname = 'Yusuf' , sure.ename = 'Joseph' WHERE sure.index = 12 LIMIT 1;
UPDATE sure SET sure.tname = 'Ar-Ra\'d' , sure.ename = 'The Thunder' WHERE sure.index = 13 LIMIT 1;
UPDATE sure SET sure.tname = 'Ibrahim' , sure.ename = 'Abrahim' WHERE sure.index = 14 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Hijr' , sure.ename = 'The Rocky Tract' WHERE sure.index = 15 LIMIT 1;
UPDATE sure SET sure.tname = 'An-Nahl' , sure.ename = 'The Bee' WHERE sure.index = 16 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Isra' , sure.ename = 'The Night Journey' WHERE sure.index = 17 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Kahf' , sure.ename = 'The Cave' WHERE sure.index = 18 LIMIT 1;
UPDATE sure SET sure.tname = 'Maryam' , sure.ename = 'Mary' WHERE sure.index = 19 LIMIT 1;
UPDATE sure SET sure.tname = 'Taha' , sure.ename = 'Ta-Ha' WHERE sure.index = 20 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Anbya' , sure.ename = 'The Prophets' WHERE sure.index = 21 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Haj' , sure.ename = 'The Pilgrimage' WHERE sure.index = 22 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Mu\'minun' , sure.ename = 'The Believers' WHERE sure.index = 23 LIMIT 1;
UPDATE sure SET sure.tname = 'An-Nur' , sure.ename = 'The Light' WHERE sure.index = 24 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Furqan' , sure.ename = 'The Criterian' WHERE sure.index = 25 LIMIT 1;
UPDATE sure SET sure.tname = 'Ash-Shu\'ara' , sure.ename = 'The Poets' WHERE sure.index = 26 LIMIT 1;
UPDATE sure SET sure.tname = 'An-Naml' , sure.ename = 'The Ant' WHERE sure.index = 27 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Qasas' , sure.ename = 'The Stories' WHERE sure.index = 28 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-\'Ankabut' , sure.ename = 'The Spider' WHERE sure.index = 29 LIMIT 1;
UPDATE sure SET sure.tname = 'Ar-Rum' , sure.ename = 'The Romans' WHERE sure.index = 30 LIMIT 1;
UPDATE sure SET sure.tname = 'Luqman' , sure.ename = 'Luqman' WHERE sure.index = 31 LIMIT 1;
UPDATE sure SET sure.tname = 'As-Sajdah' , sure.ename = 'The Prostration' WHERE sure.index = 32 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Ahzab' , sure.ename = 'The Combined Forces' WHERE sure.index = 33 LIMIT 1;
UPDATE sure SET sure.tname = 'Saba' , sure.ename = 'Sheba' WHERE sure.index = 34 LIMIT 1;
UPDATE sure SET sure.tname = 'Fatir' , sure.ename = 'Originator' WHERE sure.index = 35 LIMIT 1;
UPDATE sure SET sure.tname = 'Ya-Sin' , sure.ename = 'Ya Sin' WHERE sure.index = 36 LIMIT 1;
UPDATE sure SET sure.tname = 'As-Saffat' , sure.ename = 'Those who set the Ranks' WHERE sure.index = 37 LIMIT 1;
UPDATE sure SET sure.tname = 'Sad' , sure.ename = 'The Letter \'Saad\'' WHERE sure.index = 38 LIMIT 1;
UPDATE sure SET sure.tname = 'Az-Zumar' , sure.ename = 'The Troops' WHERE sure.index = 39 LIMIT 1;
UPDATE sure SET sure.tname = 'Ghafir' , sure.ename = 'The Forgiver' WHERE sure.index = 40 LIMIT 1;
UPDATE sure SET sure.tname = 'Fussilat' , sure.ename = 'Explained in Detail' WHERE sure.index = 41 LIMIT 1;
UPDATE sure SET sure.tname = 'Ash-Shuraa' , sure.ename = 'The Consultation' WHERE sure.index = 42 LIMIT 1;
UPDATE sure SET sure.tname = 'Az-Zukhruf' , sure.ename = 'The Ornaments of Gold' WHERE sure.index = 43 LIMIT 1;
UPDATE sure SET sure.tname = 'Ad-Dukhan' , sure.ename = 'The Smoke' WHERE sure.index = 44 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Jathiyah' , sure.ename = 'The Crouching' WHERE sure.index = 45 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Ahqaf' , sure.ename = 'The Wind-Curved Sandhills' WHERE sure.index = 46 LIMIT 1;
UPDATE sure SET sure.tname = 'Muhammad' , sure.ename = 'Muhammad' WHERE sure.index = 47 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Fath' , sure.ename = 'The Victory' WHERE sure.index = 48 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Hujurat' , sure.ename = 'The Rooms' WHERE sure.index = 49 LIMIT 1;
UPDATE sure SET sure.tname = 'Qaf' , sure.ename = 'The Letter \'Qaf\'' WHERE sure.index = 50 LIMIT 1;
UPDATE sure SET sure.tname = 'Adh-Dhariyat' , sure.ename = 'The Winnowing Winds' WHERE sure.index = 51 LIMIT 1;
UPDATE sure SET sure.tname = 'At-Tur' , sure.ename = 'The Mount' WHERE sure.index = 52 LIMIT 1;
UPDATE sure SET sure.tname = 'An-Najm' , sure.ename = 'The Star' WHERE sure.index = 53 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Qamar' , sure.ename = 'The Moon' WHERE sure.index = 54 LIMIT 1;
UPDATE sure SET sure.tname = 'Ar-Rahman' , sure.ename = 'The Beneficent' WHERE sure.index = 55 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Waqi\'ah' , sure.ename = 'The Inevitable' WHERE sure.index = 56 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Hadid' , sure.ename = 'The Iron' WHERE sure.index = 57 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Mujadila' , sure.ename = 'The Pleading Woman' WHERE sure.index = 58 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Hashr' , sure.ename = 'The Exile' WHERE sure.index = 59 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Mumtahanah' , sure.ename = 'She that is to be examined' WHERE sure.index = 60 LIMIT 1;
UPDATE sure SET sure.tname = 'As-Saf' , sure.ename = 'The Ranks' WHERE sure.index = 61 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Jumu\'ah' , sure.ename = 'The Congregation, Friday' WHERE sure.index = 62 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Munafiqun' , sure.ename = 'The Hypocrites' WHERE sure.index = 63 LIMIT 1;
UPDATE sure SET sure.tname = 'At-Taghabun' , sure.ename = 'The Mutual Disillusion' WHERE sure.index = 64 LIMIT 1;
UPDATE sure SET sure.tname = 'At-Talaq' , sure.ename = 'The Divorce' WHERE sure.index = 65 LIMIT 1;
UPDATE sure SET sure.tname = 'At-Tahrim' , sure.ename = 'The Prohibtiion' WHERE sure.index = 66 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Mulk' , sure.ename = 'The Sovereignty' WHERE sure.index = 67 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Qalam' , sure.ename = 'The Pen' WHERE sure.index = 68 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Haqqah' , sure.ename = 'The Reality' WHERE sure.index = 69 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Ma\'arij' , sure.ename = 'The Ascending Stairways' WHERE sure.index = 70 LIMIT 1;
UPDATE sure SET sure.tname = 'Nuh' , sure.ename = 'Noah' WHERE sure.index = 71 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Jinn' , sure.ename = 'The Jinn' WHERE sure.index = 72 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Muzzammil' , sure.ename = 'The Enshrouded One' WHERE sure.index = 73 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Muddaththir' , sure.ename = 'The Cloaked One' WHERE sure.index = 74 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Qiyamah' , sure.ename = 'The Resurrection' WHERE sure.index = 75 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Insan' , sure.ename = 'The Man' WHERE sure.index = 76 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Mursalat' , sure.ename = 'The Emissaries' WHERE sure.index = 77 LIMIT 1;
UPDATE sure SET sure.tname = 'An-Naba' , sure.ename = 'The Tidings' WHERE sure.index = 78 LIMIT 1;
UPDATE sure SET sure.tname = 'An-Nazi\'at' , sure.ename = 'Those who drag forth' WHERE sure.index = 79 LIMIT 1;
UPDATE sure SET sure.tname = '\'Abasa' , sure.ename = 'He Frowned' WHERE sure.index = 80 LIMIT 1;
UPDATE sure SET sure.tname = 'At-Takwir' , sure.ename = 'The Overthrowing' WHERE sure.index = 81 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Infitar' , sure.ename = 'The Cleaving' WHERE sure.index = 82 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Mutaffifin' , sure.ename = 'The Defrauding' WHERE sure.index = 83 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Inshiqaq' , sure.ename = 'The Sundering' WHERE sure.index = 84 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Buruj' , sure.ename = 'The Mansions of the Stars' WHERE sure.index = 85 LIMIT 1;
UPDATE sure SET sure.tname = 'At-Tariq' , sure.ename = 'The Nightcommer' WHERE sure.index = 86 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-A\'la' , sure.ename = 'The Most High' WHERE sure.index = 87 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Ghashiyah' , sure.ename = 'The Overwhelming' WHERE sure.index = 88 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Fajr' , sure.ename = 'The Dawn' WHERE sure.index = 89 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Balad' , sure.ename = 'The City' WHERE sure.index = 90 LIMIT 1;
UPDATE sure SET sure.tname = 'Ash-Shams' , sure.ename = 'The Sun' WHERE sure.index = 91 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Layl' , sure.ename = 'The Night' WHERE sure.index = 92 LIMIT 1;
UPDATE sure SET sure.tname = 'Ad-Duhaa' , sure.ename = 'The Morning Hours' WHERE sure.index = 93 LIMIT 1;
UPDATE sure SET sure.tname = 'Ash-Sharh' , sure.ename = 'The Relief' WHERE sure.index = 94 LIMIT 1;
UPDATE sure SET sure.tname = 'At-Tin' , sure.ename = 'The Fig' WHERE sure.index = 95 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-\'Alaq' , sure.ename = 'The Clot' WHERE sure.index = 96 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Qadr' , sure.ename = 'The Power' WHERE sure.index = 97 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Bayyinah' , sure.ename = 'The Clear Proof' WHERE sure.index = 98 LIMIT 1;
UPDATE sure SET sure.tname = 'Az-Zalzalah' , sure.ename = 'The Earthquake' WHERE sure.index = 99 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-\'Adiyat' , sure.ename = 'The Courser' WHERE sure.index = 100 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Qari\'ah' , sure.ename = 'The Calamity' WHERE sure.index = 101 LIMIT 1;
UPDATE sure SET sure.tname = 'At-Takathur' , sure.ename = 'The Rivalry in world increase' WHERE sure.index = 102 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-\'Asr' , sure.ename = 'The Declining Day' WHERE sure.index = 103 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Humazah' , sure.ename = 'The Traducer' WHERE sure.index = 104 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Fil' , sure.ename = 'The Elephant' WHERE sure.index = 105 LIMIT 1;
UPDATE sure SET sure.tname = 'Quraysh' , sure.ename = 'Quraysh' WHERE sure.index = 106 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Ma\'un' , sure.ename = 'The Small Kindesses' WHERE sure.index = 107 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Kawthar' , sure.ename = 'The Abundance' WHERE sure.index = 108 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Kafirun' , sure.ename = 'The Disbelievers' WHERE sure.index = 109 LIMIT 1;
UPDATE sure SET sure.tname = 'An-Nasr' , sure.ename = 'The Divine Support' WHERE sure.index = 110 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Masad' , sure.ename = 'The Palm Fiber' WHERE sure.index = 111 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Ikhlas' , sure.ename = 'The Sincerity' WHERE sure.index = 112 LIMIT 1;
UPDATE sure SET sure.tname = 'Al-Falaq' , sure.ename = 'The Daybreak' WHERE sure.index = 113 LIMIT 1;
UPDATE sure SET sure.tname = 'An-Nas' , sure.ename = 'The Mankind' WHERE sure.index = 114 LIMIT 1;