-- multi_query
UPDATE quran_text SET quran_text.text = 'الٓمٓ' WHERE quran_text.index = 8 AND quran_text.sura = 2 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'الٓمٓ' WHERE quran_text.index = 294 AND quran_text.sura = 3 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'يَٰٓأَيُّهَا ٱلنَّاسُ ٱتَّقُوا۟ رَبَّكُمُ ٱلَّذِى خَلَقَكُم مِّن نَّفْسٍ وَٰحِدَةٍ وَخَلَقَ مِنْهَا زَوْجَهَا وَبَثَّ مِنْهُمَا رِجَالًا كَثِيرًا وَنِسَآءً وَٱتَّقُوا۟ ٱللَّهَ ٱلَّذِى تَسَآءَلُونَ بِهِۦ وَٱلْأَرْحَامَ إِنَّ ٱللَّهَ كَانَ عَلَيْكُمْ رَقِيبًا' WHERE quran_text.index = 494 AND quran_text.sura = 4 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوٓا۟ أَوْفُوا۟ بِٱلْعُقُودِ أُحِلَّتْ لَكُم بَهِيمَةُ ٱلْأَنْعَٰمِ إِلَّا مَا يُتْلَىٰ عَلَيْكُمْ غَيْرَ مُحِلِّى ٱلصَّيْدِ وَأَنتُمْ حُرُمٌ إِنَّ ٱللَّهَ يَحْكُمُ مَا يُرِيدُ' WHERE quran_text.index = 670 AND quran_text.sura = 5 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'ٱلْحَمْدُ لِلَّهِ ٱلَّذِى خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ وَجَعَلَ ٱلظُّلُمَٰتِ وَٱلنُّورَ ثُمَّ ٱلَّذِينَ كَفَرُوا۟ بِرَبِّهِمْ يَعْدِلُونَ' WHERE quran_text.index = 790 AND quran_text.sura = 6 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'الٓمٓصٓ' WHERE quran_text.index = 955 AND quran_text.sura = 7 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'يَسْـَٔلُونَكَ عَنِ ٱلْأَنفَالِ قُلِ ٱلْأَنفَالُ لِلَّهِ وَٱلرَّسُولِ فَٱتَّقُوا۟ ٱللَّهَ وَأَصْلِحُوا۟ ذَاتَ بَيْنِكُمْ وَأَطِيعُوا۟ ٱللَّهَ وَرَسُولَهُۥٓ إِن كُنتُم مُّؤْمِنِينَ' WHERE quran_text.index = 1161 AND quran_text.sura = 8 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'الٓر تِلْكَ ءَايَٰتُ ٱلْكِتَٰبِ ٱلْحَكِيمِ' WHERE quran_text.index = 1365 AND quran_text.sura = 10 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'الٓر كِتَٰبٌ أُحْكِمَتْ ءَايَٰتُهُۥ ثُمَّ فُصِّلَتْ مِن لَّدُنْ حَكِيمٍ خَبِيرٍ' WHERE quran_text.index = 1474 AND quran_text.sura = 11 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'الٓر تِلْكَ ءَايَٰتُ ٱلْكِتَٰبِ ٱلْمُبِينِ' WHERE quran_text.index = 1597 AND quran_text.sura = 12 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'الٓمٓر تِلْكَ ءَايَٰتُ ٱلْكِتَٰبِ وَٱلَّذِىٓ أُنزِلَ إِلَيْكَ مِن رَّبِّكَ ٱلْحَقُّ وَلَٰكِنَّ أَكْثَرَ ٱلنَّاسِ لَا يُؤْمِنُونَ' WHERE quran_text.index = 1708 AND quran_text.sura = 13 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'الٓر كِتَٰبٌ أَنزَلْنَٰهُ إِلَيْكَ لِتُخْرِجَ ٱلنَّاسَ مِنَ ٱلظُّلُمَٰتِ إِلَى ٱلنُّورِ بِإِذْنِ رَبِّهِمْ إِلَىٰ صِرَٰطِ ٱلْعَزِيزِ ٱلْحَمِيدِ' WHERE quran_text.index = 1751 AND quran_text.sura = 14 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'الٓر تِلْكَ ءَايَٰتُ ٱلْكِتَٰبِ وَقُرْءَانٍ مُّبِينٍ' WHERE quran_text.index = 1803 AND quran_text.sura = 15 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'أَتَىٰٓ أَمْرُ ٱللَّهِ فَلَا تَسْتَعْجِلُوهُ سُبْحَٰنَهُۥ وَتَعَٰلَىٰ عَمَّا يُشْرِكُونَ' WHERE quran_text.index = 1902 AND quran_text.sura = 16 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'سُبْحَٰنَ ٱلَّذِىٓ أَسْرَىٰ بِعَبْدِهِۦ لَيْلًا مِّنَ ٱلْمَسْجِدِ ٱلْحَرَامِ إِلَى ٱلْمَسْجِدِ ٱلْأَقْصَا ٱلَّذِى بَٰرَكْنَا حَوْلَهُۥ لِنُرِيَهُۥ مِنْ ءَايَٰتِنَآ إِنَّهُۥ هُوَ ٱلسَّمِيعُ ٱلْبَصِيرُ' WHERE quran_text.index = 2030 AND quran_text.sura = 17 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'ٱلْحَمْدُ لِلَّهِ ٱلَّذِىٓ أَنزَلَ عَلَىٰ عَبْدِهِ ٱلْكِتَٰبَ وَلَمْ يَجْعَل لَّهُۥ عِوَجَا' WHERE quran_text.index = 2141 AND quran_text.sura = 18 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'كٓهيعٓصٓ' WHERE quran_text.index = 2251 AND quran_text.sura = 19 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'طه' WHERE quran_text.index = 2349 AND quran_text.sura = 20 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'ٱقْتَرَبَ لِلنَّاسِ حِسَابُهُمْ وَهُمْ فِى غَفْلَةٍ مُّعْرِضُونَ' WHERE quran_text.index = 2484 AND quran_text.sura = 21 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'يَٰٓأَيُّهَا ٱلنَّاسُ ٱتَّقُوا۟ رَبَّكُمْ إِنَّ زَلْزَلَةَ ٱلسَّاعَةِ شَىْءٌ عَظِيمٌ' WHERE quran_text.index = 2596 AND quran_text.sura = 22 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'قَدْ أَفْلَحَ ٱلْمُؤْمِنُونَ' WHERE quran_text.index = 2674 AND quran_text.sura = 23 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'سُورَةٌ أَنزَلْنَٰهَا وَفَرَضْنَٰهَا وَأَنزَلْنَا فِيهَآ ءَايَٰتٍۭ بَيِّنَٰتٍ لَّعَلَّكُمْ تَذَكَّرُونَ' WHERE quran_text.index = 2792 AND quran_text.sura = 24 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'تَبَارَكَ ٱلَّذِى نَزَّلَ ٱلْفُرْقَانَ عَلَىٰ عَبْدِهِۦ لِيَكُونَ لِلْعَٰلَمِينَ نَذِيرًا' WHERE quran_text.index = 2856 AND quran_text.sura = 25 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'طسٓمٓ' WHERE quran_text.index = 2933 AND quran_text.sura = 26 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'طسٓ تِلْكَ ءَايَٰتُ ٱلْقُرْءَانِ وَكِتَابٍ مُّبِينٍ' WHERE quran_text.index = 3160 AND quran_text.sura = 27 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'طسٓمٓ' WHERE quran_text.index = 3253 AND quran_text.sura = 28 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'الٓمٓ' WHERE quran_text.index = 3341 AND quran_text.sura = 29 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'الٓمٓ' WHERE quran_text.index = 3410 AND quran_text.sura = 30 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'الٓمٓ' WHERE quran_text.index = 3470 AND quran_text.sura = 31 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'الٓمٓ' WHERE quran_text.index = 3504 AND quran_text.sura = 32 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'يَٰٓأَيُّهَا ٱلنَّبِىُّ ٱتَّقِ ٱللَّهَ وَلَا تُطِعِ ٱلْكَٰفِرِينَ وَٱلْمُنَٰفِقِينَ إِنَّ ٱللَّهَ كَانَ عَلِيمًا حَكِيمًا' WHERE quran_text.index = 3534 AND quran_text.sura = 33 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'ٱلْحَمْدُ لِلَّهِ ٱلَّذِى لَهُۥ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ وَلَهُ ٱلْحَمْدُ فِى ٱلْءَاخِرَةِ وَهُوَ ٱلْحَكِيمُ ٱلْخَبِيرُ' WHERE quran_text.index = 3607 AND quran_text.sura = 34 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'ٱلْحَمْدُ لِلَّهِ فَاطِرِ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ جَاعِلِ ٱلْمَلَٰٓئِكَةِ رُسُلًا أُو۟لِىٓ أَجْنِحَةٍ مَّثْنَىٰ وَثُلَٰثَ وَرُبَٰعَ يَزِيدُ فِى ٱلْخَلْقِ مَا يَشَآءُ إِنَّ ٱللَّهَ عَلَىٰ كُلِّ شَىْءٍ قَدِيرٌ' WHERE quran_text.index = 3661 AND quran_text.sura = 35 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'يسٓ' WHERE quran_text.index = 3706 AND quran_text.sura = 36 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'وَٱلصَّٰٓفَّٰتِ صَفًّا' WHERE quran_text.index = 3789 AND quran_text.sura = 37 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'صٓ وَٱلْقُرْءَانِ ذِى ٱلذِّكْرِ' WHERE quran_text.index = 3971 AND quran_text.sura = 38 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'تَنزِيلُ ٱلْكِتَٰبِ مِنَ ٱللَّهِ ٱلْعَزِيزِ ٱلْحَكِيمِ' WHERE quran_text.index = 4059 AND quran_text.sura = 39 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'حمٓ' WHERE quran_text.index = 4134 AND quran_text.sura = 40 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'حمٓ' WHERE quran_text.index = 4219 AND quran_text.sura = 41 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'حمٓ' WHERE quran_text.index = 4273 AND quran_text.sura = 42 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'حمٓ' WHERE quran_text.index = 4326 AND quran_text.sura = 43 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'حمٓ' WHERE quran_text.index = 4415 AND quran_text.sura = 44 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'حمٓ' WHERE quran_text.index = 4474 AND quran_text.sura = 45 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'حمٓ' WHERE quran_text.index = 4511 AND quran_text.sura = 46 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'ٱلَّذِينَ كَفَرُوا۟ وَصَدُّوا۟ عَن سَبِيلِ ٱللَّهِ أَضَلَّ أَعْمَٰلَهُمْ' WHERE quran_text.index = 4546 AND quran_text.sura = 47 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'إِنَّا فَتَحْنَا لَكَ فَتْحًا مُّبِينًا' WHERE quran_text.index = 4584 AND quran_text.sura = 48 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ لَا تُقَدِّمُوا۟ بَيْنَ يَدَىِ ٱللَّهِ وَرَسُولِهِۦ وَٱتَّقُوا۟ ٱللَّهَ إِنَّ ٱللَّهَ سَمِيعٌ عَلِيمٌ' WHERE quran_text.index = 4613 AND quran_text.sura = 49 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'قٓ وَٱلْقُرْءَانِ ٱلْمَجِيدِ' WHERE quran_text.index = 4631 AND quran_text.sura = 50 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'وَٱلذَّٰرِيَٰتِ ذَرْوًا' WHERE quran_text.index = 4676 AND quran_text.sura = 51 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'وَٱلطُّورِ' WHERE quran_text.index = 4736 AND quran_text.sura = 52 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'وَٱلنَّجْمِ إِذَا هَوَىٰ' WHERE quran_text.index = 4785 AND quran_text.sura = 53 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'ٱقْتَرَبَتِ ٱلسَّاعَةُ وَٱنشَقَّ ٱلْقَمَرُ' WHERE quran_text.index = 4847 AND quran_text.sura = 54 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'ٱلرَّحْمَٰنُ' WHERE quran_text.index = 4902 AND quran_text.sura = 55 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'إِذَا وَقَعَتِ ٱلْوَاقِعَةُ' WHERE quran_text.index = 4980 AND quran_text.sura = 56 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'سَبَّحَ لِلَّهِ مَا فِى ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ وَهُوَ ٱلْعَزِيزُ ٱلْحَكِيمُ' WHERE quran_text.index = 5076 AND quran_text.sura = 57 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'قَدْ سَمِعَ ٱللَّهُ قَوْلَ ٱلَّتِى تُجَٰدِلُكَ فِى زَوْجِهَا وَتَشْتَكِىٓ إِلَى ٱللَّهِ وَٱللَّهُ يَسْمَعُ تَحَاوُرَكُمَآ إِنَّ ٱللَّهَ سَمِيعٌۢ بَصِيرٌ' WHERE quran_text.index = 5105 AND quran_text.sura = 58 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'سَبَّحَ لِلَّهِ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ وَهُوَ ٱلْعَزِيزُ ٱلْحَكِيمُ' WHERE quran_text.index = 5127 AND quran_text.sura = 59 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ لَا تَتَّخِذُوا۟ عَدُوِّى وَعَدُوَّكُمْ أَوْلِيَآءَ تُلْقُونَ إِلَيْهِم بِٱلْمَوَدَّةِ وَقَدْ كَفَرُوا۟ بِمَا جَآءَكُم مِّنَ ٱلْحَقِّ يُخْرِجُونَ ٱلرَّسُولَ وَإِيَّاكُمْ أَن تُؤْمِنُوا۟ بِٱللَّهِ رَبِّكُمْ إِن كُنتُمْ خَرَجْتُمْ جِهَٰدًا فِى سَبِيلِى وَٱبْتِغَآءَ مَرْضَاتِى تُسِرُّونَ إِلَيْهِم بِٱلْمَوَدَّةِ وَأَنَا۠ أَعْلَمُ بِمَآ أَخْفَيْتُمْ وَمَآ أَعْلَنتُمْ وَمَن يَفْعَلْهُ مِنكُمْ فَقَدْ ضَلَّ سَوَآءَ ٱلسَّبِيلِ' WHERE quran_text.index = 5151 AND quran_text.sura = 60 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'سَبَّحَ لِلَّهِ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ وَهُوَ ٱلْعَزِيزُ ٱلْحَكِيمُ' WHERE quran_text.index = 5164 AND quran_text.sura = 61 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'يُسَبِّحُ لِلَّهِ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ ٱلْمَلِكِ ٱلْقُدُّوسِ ٱلْعَزِيزِ ٱلْحَكِيمِ' WHERE quran_text.index = 5178 AND quran_text.sura = 62 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'إِذَا جَآءَكَ ٱلْمُنَٰفِقُونَ قَالُوا۟ نَشْهَدُ إِنَّكَ لَرَسُولُ ٱللَّهِ وَٱللَّهُ يَعْلَمُ إِنَّكَ لَرَسُولُهُۥ وَٱللَّهُ يَشْهَدُ إِنَّ ٱلْمُنَٰفِقِينَ لَكَٰذِبُونَ' WHERE quran_text.index = 5189 AND quran_text.sura = 63 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'يُسَبِّحُ لِلَّهِ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ لَهُ ٱلْمُلْكُ وَلَهُ ٱلْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَىْءٍ قَدِيرٌ' WHERE quran_text.index = 5200 AND quran_text.sura = 64 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'يَٰٓأَيُّهَا ٱلنَّبِىُّ إِذَا طَلَّقْتُمُ ٱلنِّسَآءَ فَطَلِّقُوهُنَّ لِعِدَّتِهِنَّ وَأَحْصُوا۟ ٱلْعِدَّةَ وَٱتَّقُوا۟ ٱللَّهَ رَبَّكُمْ لَا تُخْرِجُوهُنَّ مِنۢ بُيُوتِهِنَّ وَلَا يَخْرُجْنَ إِلَّآ أَن يَأْتِينَ بِفَٰحِشَةٍ مُّبَيِّنَةٍ وَتِلْكَ حُدُودُ ٱللَّهِ وَمَن يَتَعَدَّ حُدُودَ ٱللَّهِ فَقَدْ ظَلَمَ نَفْسَهُۥ لَا تَدْرِى لَعَلَّ ٱللَّهَ يُحْدِثُ بَعْدَ ذَٰلِكَ أَمْرًا' WHERE quran_text.index = 5218 AND quran_text.sura = 65 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'يَٰٓأَيُّهَا ٱلنَّبِىُّ لِمَ تُحَرِّمُ مَآ أَحَلَّ ٱللَّهُ لَكَ تَبْتَغِى مَرْضَاتَ أَزْوَٰجِكَ وَٱللَّهُ غَفُورٌ رَّحِيمٌ' WHERE quran_text.index = 5230 AND quran_text.sura = 66 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'تَبَٰرَكَ ٱلَّذِى بِيَدِهِ ٱلْمُلْكُ وَهُوَ عَلَىٰ كُلِّ شَىْءٍ قَدِيرٌ' WHERE quran_text.index = 5242 AND quran_text.sura = 67 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'نٓ وَٱلْقَلَمِ وَمَا يَسْطُرُونَ' WHERE quran_text.index = 5272 AND quran_text.sura = 68 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'ٱلْحَآقَّةُ' WHERE quran_text.index = 5324 AND quran_text.sura = 69 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'سَأَلَ سَآئِلٌۢ بِعَذَابٍ وَاقِعٍ' WHERE quran_text.index = 5376 AND quran_text.sura = 70 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'إِنَّآ أَرْسَلْنَا نُوحًا إِلَىٰ قَوْمِهِۦٓ أَنْ أَنذِرْ قَوْمَكَ مِن قَبْلِ أَن يَأْتِيَهُمْ عَذَابٌ أَلِيمٌ' WHERE quran_text.index = 5420 AND quran_text.sura = 71 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'قُلْ أُوحِىَ إِلَىَّ أَنَّهُ ٱسْتَمَعَ نَفَرٌ مِّنَ ٱلْجِنِّ فَقَالُوٓا۟ إِنَّا سَمِعْنَا قُرْءَانًا عَجَبًا' WHERE quran_text.index = 5448 AND quran_text.sura = 72 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'يَٰٓأَيُّهَا ٱلْمُزَّمِّلُ' WHERE quran_text.index = 5476 AND quran_text.sura = 73 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'يَٰٓأَيُّهَا ٱلْمُدَّثِّرُ' WHERE quran_text.index = 5496 AND quran_text.sura = 74 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'لَآ أُقْسِمُ بِيَوْمِ ٱلْقِيَٰمَةِ' WHERE quran_text.index = 5552 AND quran_text.sura = 75 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'هَلْ أَتَىٰ عَلَى ٱلْإِنسَٰنِ حِينٌ مِّنَ ٱلدَّهْرِ لَمْ يَكُن شَيْـًٔا مَّذْكُورًا' WHERE quran_text.index = 5592 AND quran_text.sura = 76 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'وَٱلْمُرْسَلَٰتِ عُرْفًا' WHERE quran_text.index = 5623 AND quran_text.sura = 77 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'عَمَّ يَتَسَآءَلُونَ' WHERE quran_text.index = 5673 AND quran_text.sura = 78 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'وَٱلنَّٰزِعَٰتِ غَرْقًا' WHERE quran_text.index = 5713 AND quran_text.sura = 79 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'عَبَسَ وَتَوَلَّىٰٓ' WHERE quran_text.index = 5759 AND quran_text.sura = 80 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'إِذَا ٱلشَّمْسُ كُوِّرَتْ' WHERE quran_text.index = 5801 AND quran_text.sura = 81 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'إِذَا ٱلسَّمَآءُ ٱنفَطَرَتْ' WHERE quran_text.index = 5830 AND quran_text.sura = 82 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'وَيْلٌ لِّلْمُطَفِّفِينَ' WHERE quran_text.index = 5849 AND quran_text.sura = 83 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'إِذَا ٱلسَّمَآءُ ٱنشَقَّتْ' WHERE quran_text.index = 5885 AND quran_text.sura = 84 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'وَٱلسَّمَآءِ ذَاتِ ٱلْبُرُوجِ' WHERE quran_text.index = 5910 AND quran_text.sura = 85 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'وَٱلسَّمَآءِ وَٱلطَّارِقِ' WHERE quran_text.index = 5932 AND quran_text.sura = 86 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'سَبِّحِ ٱسْمَ رَبِّكَ ٱلْأَعْلَى' WHERE quran_text.index = 5949 AND quran_text.sura = 87 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'هَلْ أَتَىٰكَ حَدِيثُ ٱلْغَٰشِيَةِ' WHERE quran_text.index = 5968 AND quran_text.sura = 88 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'وَٱلْفَجْرِ' WHERE quran_text.index = 5994 AND quran_text.sura = 89 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'لَآ أُقْسِمُ بِهَٰذَا ٱلْبَلَدِ' WHERE quran_text.index = 6024 AND quran_text.sura = 90 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'وَٱلشَّمْسِ وَضُحَىٰهَا' WHERE quran_text.index = 6044 AND quran_text.sura = 91 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'وَٱلَّيْلِ إِذَا يَغْشَىٰ' WHERE quran_text.index = 6059 AND quran_text.sura = 92 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'وَٱلضُّحَىٰ' WHERE quran_text.index = 6080 AND quran_text.sura = 93 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'أَلَمْ نَشْرَحْ لَكَ صَدْرَكَ' WHERE quran_text.index = 6091 AND quran_text.sura = 94 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'وَٱلتِّينِ وَٱلزَّيْتُونِ' WHERE quran_text.index = 6099 AND quran_text.sura = 95 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'ٱقْرَأْ بِٱسْمِ رَبِّكَ ٱلَّذِى خَلَقَ' WHERE quran_text.index = 6107 AND quran_text.sura = 96 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'لَمْ يَكُنِ ٱلَّذِينَ كَفَرُوا۟ مِنْ أَهْلِ ٱلْكِتَٰبِ وَٱلْمُشْرِكِينَ مُنفَكِّينَ حَتَّىٰ تَأْتِيَهُمُ ٱلْبَيِّنَةُ' WHERE quran_text.index = 6131 AND quran_text.sura = 98 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'إِذَا زُلْزِلَتِ ٱلْأَرْضُ زِلْزَالَهَا' WHERE quran_text.index = 6139 AND quran_text.sura = 99 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'وَٱلْعَٰدِيَٰتِ ضَبْحًا' WHERE quran_text.index = 6147 AND quran_text.sura = 100 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'ٱلْقَارِعَةُ' WHERE quran_text.index = 6158 AND quran_text.sura = 101 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'أَلْهَىٰكُمُ ٱلتَّكَاثُرُ' WHERE quran_text.index = 6169 AND quran_text.sura = 102 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'وَٱلْعَصْرِ' WHERE quran_text.index = 6177 AND quran_text.sura = 103 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'وَيْلٌ لِّكُلِّ هُمَزَةٍ لُّمَزَةٍ' WHERE quran_text.index = 6180 AND quran_text.sura = 104 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'أَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِأَصْحَٰبِ ٱلْفِيلِ' WHERE quran_text.index = 6189 AND quran_text.sura = 105 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'لِإِيلَٰفِ قُرَيْشٍ' WHERE quran_text.index = 6194 AND quran_text.sura = 106 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'أَرَءَيْتَ ٱلَّذِى يُكَذِّبُ بِٱلدِّينِ' WHERE quran_text.index = 6198 AND quran_text.sura = 107 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'إِنَّآ أَعْطَيْنَٰكَ ٱلْكَوْثَرَ' WHERE quran_text.index = 6205 AND quran_text.sura = 108 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'قُلْ يَٰٓأَيُّهَا ٱلْكَٰفِرُونَ' WHERE quran_text.index = 6208 AND quran_text.sura = 109 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'إِذَا جَآءَ نَصْرُ ٱللَّهِ وَٱلْفَتْحُ' WHERE quran_text.index = 6214 AND quran_text.sura = 110 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'تَبَّتْ يَدَآ أَبِى لَهَبٍ وَتَبَّ' WHERE quran_text.index = 6217 AND quran_text.sura = 111 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'قُلْ هُوَ ٱللَّهُ أَحَدٌ' WHERE quran_text.index = 6222 AND quran_text.sura = 112 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ' WHERE quran_text.index = 6226 AND quran_text.sura = 113 AND quran_text.aya =  1 LIMIT 1;
UPDATE quran_text SET quran_text.text = 'قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ' WHERE quran_text.index = 6231 AND quran_text.sura = 114 AND quran_text.aya =  1 LIMIT 1;



UPDATE quran_text SET quran_text.simple = 'الم' WHERE quran_text.index = 8 AND quran_text.sura = 2 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'الم' WHERE quran_text.index = 294 AND quran_text.sura = 3 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'يا أيها الناس اتقوا ربكم الذي خلقكم من نفس واحدة وخلق منها زوجها وبث منهما رجالا كثيرا ونساء واتقوا الله الذي تساءلون به والأرحام إن الله كان عليكم رقيبا' WHERE quran_text.index = 494 AND quran_text.sura = 4 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'يا أيها الذين آمنوا أوفوا بالعقود أحلت لكم بهيمة الأنعام إلا ما يتلى عليكم غير محلي الصيد وأنتم حرم إن الله يحكم ما يريد' WHERE quran_text.index = 670 AND quran_text.sura = 5 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'الحمد لله الذي خلق السماوات والأرض وجعل الظلمات والنور ثم الذين كفروا بربهم يعدلون' WHERE quran_text.index = 790 AND quran_text.sura = 6 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'المص' WHERE quran_text.index = 955 AND quran_text.sura = 7 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'يسألونك عن الأنفال قل الأنفال لله والرسول فاتقوا الله وأصلحوا ذات بينكم وأطيعوا الله ورسوله إن كنتم مؤمنين' WHERE quran_text.index = 1161 AND quran_text.sura = 8 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'الر تلك آيات الكتاب الحكيم' WHERE quran_text.index = 1365 AND quran_text.sura = 10 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'الر كتاب أحكمت آياته ثم فصلت من لدن حكيم خبير' WHERE quran_text.index = 1474 AND quran_text.sura = 11 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'الر تلك آيات الكتاب المبين' WHERE quran_text.index = 1597 AND quran_text.sura = 12 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'المر تلك آيات الكتاب والذي أنزل إليك من ربك الحق ولكن أكثر الناس لا يؤمنون' WHERE quran_text.index = 1708 AND quran_text.sura = 13 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'الر كتاب أنزلناه إليك لتخرج الناس من الظلمات إلى النور بإذن ربهم إلى صراط العزيز الحميد' WHERE quran_text.index = 1751 AND quran_text.sura = 14 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'الر تلك آيات الكتاب وقرآن مبين' WHERE quran_text.index = 1803 AND quran_text.sura = 15 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'أتى أمر الله فلا تستعجلوه سبحانه وتعالى عما يشركون' WHERE quran_text.index = 1902 AND quran_text.sura = 16 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'سبحان الذي أسرى بعبده ليلا من المسجد الحرام إلى المسجد الأقصى الذي باركنا حوله لنريه من آياتنا إنه هو السميع البصير' WHERE quran_text.index = 2030 AND quran_text.sura = 17 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'الحمد لله الذي أنزل على عبده الكتاب ولم يجعل له عوجا' WHERE quran_text.index = 2141 AND quran_text.sura = 18 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'كهيعص' WHERE quran_text.index = 2251 AND quran_text.sura = 19 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'طه' WHERE quran_text.index = 2349 AND quran_text.sura = 20 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'اقترب للناس حسابهم وهم في غفلة معرضون' WHERE quran_text.index = 2484 AND quran_text.sura = 21 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'يا أيها الناس اتقوا ربكم إن زلزلة الساعة شيء عظيم' WHERE quran_text.index = 2596 AND quran_text.sura = 22 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'قد أفلح المؤمنون' WHERE quran_text.index = 2674 AND quran_text.sura = 23 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'سورة أنزلناها وفرضناها وأنزلنا فيها آيات بينات لعلكم تذكرون' WHERE quran_text.index = 2792 AND quran_text.sura = 24 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'تبارك الذي نزل الفرقان على عبده ليكون للعالمين نذيرا' WHERE quran_text.index = 2856 AND quran_text.sura = 25 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'طسم' WHERE quran_text.index = 2933 AND quran_text.sura = 26 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'طس تلك آيات القرآن وكتاب مبين' WHERE quran_text.index = 3160 AND quran_text.sura = 27 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'طسم' WHERE quran_text.index = 3253 AND quran_text.sura = 28 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'الم' WHERE quran_text.index = 3341 AND quran_text.sura = 29 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'الم' WHERE quran_text.index = 3410 AND quran_text.sura = 30 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'الم' WHERE quran_text.index = 3470 AND quran_text.sura = 31 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'الم' WHERE quran_text.index = 3504 AND quran_text.sura = 32 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'يا أيها النبي اتق الله ولا تطع الكافرين والمنافقين إن الله كان عليما حكيما' WHERE quran_text.index = 3534 AND quran_text.sura = 33 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'الحمد لله الذي له ما في السماوات وما في الأرض وله الحمد في الآخرة وهو الحكيم الخبير' WHERE quran_text.index = 3607 AND quran_text.sura = 34 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'الحمد لله فاطر السماوات والأرض جاعل الملائكة رسلا أولي أجنحة مثنى وثلاث ورباع يزيد في الخلق ما يشاء إن الله على كل شيء قدير' WHERE quran_text.index = 3661 AND quran_text.sura = 35 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'يس' WHERE quran_text.index = 3706 AND quran_text.sura = 36 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'والصافات صفا' WHERE quran_text.index = 3789 AND quran_text.sura = 37 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'ص والقرآن ذي الذكر' WHERE quran_text.index = 3971 AND quran_text.sura = 38 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'تنزيل الكتاب من الله العزيز الحكيم' WHERE quran_text.index = 4059 AND quran_text.sura = 39 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'حم' WHERE quran_text.index = 4134 AND quran_text.sura = 40 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'حم' WHERE quran_text.index = 4219 AND quran_text.sura = 41 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'حم' WHERE quran_text.index = 4273 AND quran_text.sura = 42 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'حم' WHERE quran_text.index = 4326 AND quran_text.sura = 43 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'حم' WHERE quran_text.index = 4415 AND quran_text.sura = 44 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'حم' WHERE quran_text.index = 4474 AND quran_text.sura = 45 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'حم' WHERE quran_text.index = 4511 AND quran_text.sura = 46 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'الذين كفروا وصدوا عن سبيل الله أضل أعمالهم' WHERE quran_text.index = 4546 AND quran_text.sura = 47 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'إنا فتحنا لك فتحا مبينا' WHERE quran_text.index = 4584 AND quran_text.sura = 48 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'يا أيها الذين آمنوا لا تقدموا بين يدي الله ورسوله واتقوا الله إن الله سميع عليم' WHERE quran_text.index = 4613 AND quran_text.sura = 49 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'ق والقرآن المجيد' WHERE quran_text.index = 4631 AND quran_text.sura = 50 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'والذاريات ذروا' WHERE quran_text.index = 4676 AND quran_text.sura = 51 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'والطور' WHERE quran_text.index = 4736 AND quran_text.sura = 52 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'والنجم إذا هوى' WHERE quran_text.index = 4785 AND quran_text.sura = 53 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'اقتربت الساعة وانشق القمر' WHERE quran_text.index = 4847 AND quran_text.sura = 54 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'الرحمن' WHERE quran_text.index = 4902 AND quran_text.sura = 55 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'إذا وقعت الواقعة' WHERE quran_text.index = 4980 AND quran_text.sura = 56 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'سبح لله ما في السماوات والأرض وهو العزيز الحكيم' WHERE quran_text.index = 5076 AND quran_text.sura = 57 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'قد سمع الله قول التي تجادلك في زوجها وتشتكي إلى الله والله يسمع تحاوركما إن الله سميع بصير' WHERE quran_text.index = 5105 AND quran_text.sura = 58 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'سبح لله ما في السماوات وما في الأرض وهو العزيز الحكيم' WHERE quran_text.index = 5127 AND quran_text.sura = 59 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'يا أيها الذين آمنوا لا تتخذوا عدوي وعدوكم أولياء تلقون إليهم بالمودة وقد كفروا بما جاءكم من الحق يخرجون الرسول وإياكم أن تؤمنوا بالله ربكم إن كنتم خرجتم جهادا في سبيلي وابتغاء مرضاتي تسرون إليهم بالمودة وأنا أعلم بما أخفيتم وما أعلنتم ومن يفعله منكم فقد ضل سواء السبيل' WHERE quran_text.index = 5151 AND quran_text.sura = 60 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'سبح لله ما في السماوات وما في الأرض وهو العزيز الحكيم' WHERE quran_text.index = 5164 AND quran_text.sura = 61 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'يسبح لله ما في السماوات وما في الأرض الملك القدوس العزيز الحكيم' WHERE quran_text.index = 5178 AND quran_text.sura = 62 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'إذا جاءك المنافقون قالوا نشهد إنك لرسول الله والله يعلم إنك لرسوله والله يشهد إن المنافقين لكاذبون' WHERE quran_text.index = 5189 AND quran_text.sura = 63 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'يسبح لله ما في السماوات وما في الأرض له الملك وله الحمد وهو على كل شيء قدير' WHERE quran_text.index = 5200 AND quran_text.sura = 64 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'يا أيها النبي إذا طلقتم النساء فطلقوهن لعدتهن وأحصوا العدة واتقوا الله ربكم لا تخرجوهن من بيوتهن ولا يخرجن إلا أن يأتين بفاحشة مبينة وتلك حدود الله ومن يتعد حدود الله فقد ظلم نفسه لا تدري لعل الله يحدث بعد ذلك أمرا' WHERE quran_text.index = 5218 AND quran_text.sura = 65 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'يا أيها النبي لم تحرم ما أحل الله لك تبتغي مرضات أزواجك والله غفور رحيم' WHERE quran_text.index = 5230 AND quran_text.sura = 66 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'تبارك الذي بيده الملك وهو على كل شيء قدير' WHERE quran_text.index = 5242 AND quran_text.sura = 67 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'ن والقلم وما يسطرون' WHERE quran_text.index = 5272 AND quran_text.sura = 68 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'الحاقة' WHERE quran_text.index = 5324 AND quran_text.sura = 69 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'سأل سائل بعذاب واقع' WHERE quran_text.index = 5376 AND quran_text.sura = 70 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'إنا أرسلنا نوحا إلى قومه أن أنذر قومك من قبل أن يأتيهم عذاب أليم' WHERE quran_text.index = 5420 AND quran_text.sura = 71 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'قل أوحي إلي أنه استمع نفر من الجن فقالوا إنا سمعنا قرآنا عجبا' WHERE quran_text.index = 5448 AND quran_text.sura = 72 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'يا أيها المزمل' WHERE quran_text.index = 5476 AND quran_text.sura = 73 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'يا أيها المدثر' WHERE quran_text.index = 5496 AND quran_text.sura = 74 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'لا أقسم بيوم القيامة' WHERE quran_text.index = 5552 AND quran_text.sura = 75 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'هل أتى على الإنسان حين من الدهر لم يكن شيئا مذكورا' WHERE quran_text.index = 5592 AND quran_text.sura = 76 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'والمرسلات عرفا' WHERE quran_text.index = 5623 AND quran_text.sura = 77 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'عم يتساءلون' WHERE quran_text.index = 5673 AND quran_text.sura = 78 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'والنازعات غرقا' WHERE quran_text.index = 5713 AND quran_text.sura = 79 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'عبس وتولى' WHERE quran_text.index = 5759 AND quran_text.sura = 80 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'إذا الشمس كورت' WHERE quran_text.index = 5801 AND quran_text.sura = 81 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'إذا السماء انفطرت' WHERE quran_text.index = 5830 AND quran_text.sura = 82 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'ويل للمطففين' WHERE quran_text.index = 5849 AND quran_text.sura = 83 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'إذا السماء انشقت' WHERE quran_text.index = 5885 AND quran_text.sura = 84 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'والسماء ذات البروج' WHERE quran_text.index = 5910 AND quran_text.sura = 85 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'والسماء والطارق' WHERE quran_text.index = 5932 AND quran_text.sura = 86 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'سبح اسم ربك الأعلى' WHERE quran_text.index = 5949 AND quran_text.sura = 87 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'هل أتاك حديث الغاشية' WHERE quran_text.index = 5968 AND quran_text.sura = 88 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'والفجر' WHERE quran_text.index = 5994 AND quran_text.sura = 89 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'لا أقسم بهذا البلد' WHERE quran_text.index = 6024 AND quran_text.sura = 90 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'والشمس وضحاها' WHERE quran_text.index = 6044 AND quran_text.sura = 91 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'والليل إذا يغشى' WHERE quran_text.index = 6059 AND quran_text.sura = 92 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'والضحى' WHERE quran_text.index = 6080 AND quran_text.sura = 93 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'ألم نشرح لك صدرك' WHERE quran_text.index = 6091 AND quran_text.sura = 94 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'والتين والزيتون' WHERE quran_text.index = 6099 AND quran_text.sura = 95 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'اقرأ باسم ربك الذي خلق' WHERE quran_text.index = 6107 AND quran_text.sura = 96 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'إنا أنزلناه في ليلة القدر' WHERE quran_text.index = 6126 AND quran_text.sura = 97 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'لم يكن الذين كفروا من أهل الكتاب والمشركين منفكين حتى تأتيهم البينة' WHERE quran_text.index = 6131 AND quran_text.sura = 98 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'إذا زلزلت الأرض زلزالها' WHERE quran_text.index = 6139 AND quran_text.sura = 99 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'والعاديات ضبحا' WHERE quran_text.index = 6147 AND quran_text.sura = 100 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'القارعة' WHERE quran_text.index = 6158 AND quran_text.sura = 101 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'ألهاكم التكاثر' WHERE quran_text.index = 6169 AND quran_text.sura = 102 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'والعصر' WHERE quran_text.index = 6177 AND quran_text.sura = 103 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'ويل لكل همزة لمزة' WHERE quran_text.index = 6180 AND quran_text.sura = 104 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'ألم تر كيف فعل ربك بأصحاب الفيل' WHERE quran_text.index = 6189 AND quran_text.sura = 105 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'لإيلاف قريش' WHERE quran_text.index = 6194 AND quran_text.sura = 106 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'أرأيت الذي يكذب بالدين' WHERE quran_text.index = 6198 AND quran_text.sura = 107 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'إنا أعطيناك الكوثر' WHERE quran_text.index = 6205 AND quran_text.sura = 108 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'قل يا أيها الكافرون' WHERE quran_text.index = 6208 AND quran_text.sura = 109 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'إذا جاء نصر الله والفتح' WHERE quran_text.index = 6214 AND quran_text.sura = 110 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'تبت يدا أبي لهب وتب' WHERE quran_text.index = 6217 AND quran_text.sura = 111 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'قل هو الله أحد' WHERE quran_text.index = 6222 AND quran_text.sura = 112 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'قل أعوذ برب الفلق' WHERE quran_text.index = 6226 AND quran_text.sura = 113 AND quran_text.aya = 1 LIMIT 1;
UPDATE quran_text SET quran_text.simple = 'قل أعوذ برب الناس' WHERE quran_text.index = 6231 AND quran_text.sura = 114 AND quran_text.aya = 1 LIMIT 1;